// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TelephoneDirectory.DbModel;

#nullable disable

namespace TelephoneDirectory.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20220603114257_person")]
    partial class person
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TelephoneDirectory.DbModel.BaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("creates_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("updates_date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("BaseEntities");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BaseEntity");
                });

            modelBuilder.Entity("TelephoneDirectory.DbModel.DetailEntities", b =>
                {
                    b.HasBaseType("TelephoneDirectory.DbModel.BaseEntity");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("DetailEntities");
                });

            modelBuilder.Entity("TelephoneDirectory.DbModel.PersonEntities", b =>
                {
                    b.HasBaseType("TelephoneDirectory.DbModel.BaseEntity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("PersonEntities");
                });

            modelBuilder.Entity("TelephoneDirectory.DbModel.TypeEntity", b =>
                {
                    b.HasBaseType("TelephoneDirectory.DbModel.BaseEntity");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TypeEntity_email");

                    b.Property<string>("number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TypeEntity_number");

                    b.HasDiscriminator().HasValue("TypeEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
